_wandb:
    value:
        cli_version: 0.23.1
        e:
            vf3z6uibn2en4hc5sl2sarh131fozinn:
                apple:
                    ecpuCores: 2
                    gpuCores: 24
                    memoryGb: 32
                    name: Apple M1 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                codePath: VectorizedTraining.py
                codePathLocal: VectorizedTraining.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "1995218165760"
                        used: "838530068480"
                email: casali.ma98@gmail.com
                executable: /Users/matthewcasali/Documents/PythonScripts/palace-ai/.venv/bin/python
                git:
                    commit: 4953cde87bf044cd4b57ad83c0fa495a72b7059b
                    remote: git@github.com:ma-casali/palace-ai.git
                host: Lucass-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/matthewcasali/Documents/PythonScripts/palace-ai/VectorizedTraining.py
                python: CPython 3.9.6
                root: /Users/matthewcasali/Documents/PythonScripts/palace-ai
                startedAt: "2026-01-13T21:42:48.579899Z"
                writerId: vf3z6uibn2en4hc5sl2sarh131fozinn
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.9.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
final_ent:
    value: 0.005
final_lr:
    value: 2.7380536548880055e-06
initial_ent:
    value: 0.01
initial_lr:
    value: 2.1715901191355137e-05
