_wandb:
    value:
        cli_version: 0.23.1
        e:
            yibu8haufj6sf72j85jhbrwa7bscez22:
                apple:
                    ecpuCores: 2
                    gpuCores: 24
                    memoryGb: 32
                    name: Apple M1 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                codePath: VectorizedTraining.py
                codePathLocal: VectorizedTraining.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "1995218165760"
                        used: "838252920832"
                email: casali.ma98@gmail.com
                executable: /Users/matthewcasali/Documents/PythonScripts/palace-ai/.venv/bin/python
                git:
                    commit: 4953cde87bf044cd4b57ad83c0fa495a72b7059b
                    remote: git@github.com:ma-casali/palace-ai.git
                host: Lucass-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/matthewcasali/Documents/PythonScripts/palace-ai/VectorizedTraining.py
                python: CPython 3.9.6
                root: /Users/matthewcasali/Documents/PythonScripts/palace-ai
                startedAt: "2026-01-13T19:02:38.309620Z"
                writerId: yibu8haufj6sf72j85jhbrwa7bscez22
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 256
entropy_end:
    value: 0.005
entropy_start:
    value: 0.05
final_lr:
    value: 1e-06
initial_lr:
    value: 0.0001
num_generations:
    value: 1000
sequence_length:
    value: 6
